apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanager.storage }}
  storageClassName: {{ .Values.global.storageClass }}
