apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
