apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use "nlb" for AWS or remove for default LB
spec:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80   # External Port
      targetPort: 3000  # Internal Grafana Port
