apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pushgateway-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pushgateway.storage }}
  storageClassName: {{ .Values.global.storageClass }}
