apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "node-exporter"
        static_configs:
          - targets: ["node-exporter:9100"]

      - job_name: "pushgateway"
        static_configs:
          - targets: ["pushgateway:9091"]

      - job_name: "kubernetes-apiservers"
        kubernetes_sd_configs:
          - role: endpoints

      - job_name: "kubernetes-nodes"
        kubernetes_sd_configs:
          - role: node

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod

      - job_name: "kubernetes-services"
        kubernetes_sd_configs:
          - role: service
